---
title: "Stage 4: DESeq2 Differential Expression"
author: "Bo Yu, Si Liu, Wei Sun"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: journal
    highlight: tango
    toc: true
    toc_depth: 2
    toc_float:
      collapsed: true
      smooth_scroll: false
    number_sections: false
  df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(warn = 1)
```

## Load experiment object

```{r}
library(jaxExperiment)

expt_file = file.path("outputs", "experiment.rds")
expt = load_experiment(expt_file)
expt
```

## Run DESeq2 per DE group

```{r fig.width = 4.8, fig.height=3.2}
spec4 = stage4_spec_default()
expt = stage4_run_de(expt, spec = spec4)
rep4 = stage4_report(expt)
```

## QC summary (design + filtering decisions)

```{r}
knitr::kable(rep4$qc_summary, row.names = FALSE)
```

## Contrasts (sample sizes + DE gene counts)

```{r}
knitr::kable(rep4$contrast_summary, row.names = FALSE)
```

## Save experiment object (for later stages)

```{r}
save_experiment(expt, expt_file)
```

```{r}
gc()
sessionInfo()
```
