---
title: "Check RNAseq data of 2026-01 release MSK_bulkRNAseq_ISL1_OE"
author: "Si Liu, Bo Yu, Wei Sun"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: journal
    highlight: tango
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: true
      smooth_scroll: false
    number_sections: false
  df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Check the bulk RNAseq MSK_ISL1_OE data from Jan 2026 release.

This dataset spans

* H1,
* day18, (final_timepoint: "unknown"),
* four different colonal cell lines,
* pancreatic islet,
* WT and OE of ISL1. 

## R libraries.

```{r load_libraries, warning = FALSE, message = FALSE}
library(ggplot2)
library(ggrepel)
library(ggpubr)
library(stringr)
library(MASS)
library(RColorBrewer)

library(viridis)
library(ggpointdensity)
library(dplyr)
library(data.table)
library(readxl)

path = "../../MorPhiC/data/MorPhiC_internal_releases/MorPhiC_Release_January_2026/MSK_bulkRNAseq_ISL1_OE"
dat_path = file.path(path, "processed/Tables")

metadata_path = path

meta_file = paste0(metadata_path, "/v1_MSKCC_RNAseq_ISL1oe_AnuComments_12.05_DL.xlsx")

meta_save_path = "./data/Jan_2026"
# create the directory if not exists
if (!dir.exists(meta_save_path)) {
  dir.create(meta_save_path, recursive = TRUE)
}

read_header <- function(file_name, sheet){
  
  meta_header = read_excel(file_name, sheet = sheet, 
                         skip = 3, n_max = 1, col_names = FALSE)
  meta_header = as.character(meta_header)
  meta_header = gsub("_cell_line", "", meta_header, fixed = TRUE)
  meta_header = gsub("differentiated_product.", "", meta_header, fixed = TRUE)
  meta_header = gsub(".text", "", meta_header, fixed = TRUE)
  
  meta_header
}
```

## Read in sequence file information

```{r}
seq_header = read_header(meta_file, sheet = "Sequence file")
seq_header

seq = read_excel(meta_file, sheet = "Sequence file", 
                skip = 5, col_names = FALSE)
names(seq) = seq_header
seq = as.data.frame(seq)
seq$file_id = gsub("_R(1|2)_001.fastq.gz", "", 
                   seq$sequence_file.label)
dim(seq)
seq[1:2,]

seq = unique(seq[,c("file_id", "library_preparation.label")])
dim(seq)
seq[1:2,]
length(unique(seq$library_preparation.label))
table(seq$library_preparation.label, useNA="ifany")

seq = seq[1:(nrow(seq)-2), ]
dim(seq)

# table(seq$sequence_file.run_id)
```

## Create pseudo meta data
```{r fig.width = 3, fig.height=3}

seq$clonal.label = sub("_IGO.*", "", seq$file_id)
seq$sample_id <- sub("_L00[1-8]$", "", seq$file_id)
meta = unique(seq[, c("clonal.label", "library_preparation.label", "sample_id")])

table(table(meta$clonal.label))
table(table(meta$library_preparation.label))
table(table(meta$sample_id))

colnames(meta)[2] = "label"
meta[1:6,]

meta$timepoint_value = 18
meta$model_system = "Pancreatic_Islet"

meta$cell_line <- sub("-.*",  "", meta$label)   # part before "-"
meta$OE_status <- sub(".*-",  "", meta$label)   # part after "-"

table(meta$label, meta$cell_line)
table(meta$label, meta$OE_status)

meta$condition = "not applicable"

# save meta data table
fwrite(meta, file.path(meta_save_path, "MSK_bulkRNAseq_ISL1_OE_meta_data.tsv"), sep="\t")

```

## Check count data

### genesCounts.csv

```{r fig.width = 5.5, fig.height=4}
cts = fread(file.path(dat_path, "genesCounts.csv"), data.table = FALSE)
dim(cts)
cts[1:2, c(1:2, (ncol(cts)-1):ncol(cts))]

setdiff(names(cts)[-1], seq$file_id)
setdiff(seq$file_id, names(cts)[-1])

length(unique(names(cts)))

names(cts)[1:6]
names(cts)[grepl("ISL1-BFP-1_IGO_17695_16_S6", names(cts))]

table(cts[, 2] == cts[, 3], useNA="ifany")


```



```{r}
gc()
sessionInfo()
```


